<?php

/**
 * @file
 * Module file for menu_admin_per_menu.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\menu_ui\Form\MenuLinkEditForm;
use Drupal\menu_ui\MenuForm;
use Drupal\menu_link_content\Form\MenuLinkContentForm;
use Drupal\Core\Session\AccountInterface;

/**
 * Implementation of hook_form_alter().
 */
function menu_admin_per_menu_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form_object = $form_state->getFormObject();
  if ($form_object instanceof MenuLinkEditForm
    || $form_object instanceof MenuLinkContentForm) {
    $account = \Drupal::currentUser();
    if (!$account->hasPermission('administer menu')) {
      $options = &$form['menu_parent']['#options'];
      $options = menu_admin_per_menu_filter_parent_options($account, $options);
    }
  }
  if ($form_object instanceof MenuForm) {
    $account = \Drupal::currentUser();
    if (!$account->hasPermission('administer menu')) {
      $form['id']['#access'] = FALSE;
      $form['label']['#access'] = FALSE;
      $form['description']['#access'] = FALSE;
    }
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for node_form.
 */
function menu_admin_per_menu_form_node_form_alter(&$form, FormStateInterface $form_state) {
  $account = \Drupal::currentUser();
  if (!$account->hasPermission('administer menu')) {
    $options = &$form['menu']['link']['menu_parent']['#options'];
    $options = menu_admin_per_menu_filter_parent_options($account, $options);
    $form['menu']['#access'] = count($options) > 0;

    // Remove previous default if current user cannot access it.
    $default_value = &$form['menu']['link']['menu_parent']['#default_value'];
    if (!isset($options[$default_value])) {
      $default_value = NULL;
    }
  }
}

/**
 * Removes menu items for menus a user does not have permission to access.
 *
 * @param \Drupal\Core\Session\AccountInterface
 *   The user to check for access.
 * @param array $options
 *   An array of menu item labels keyed by menu item ID.
 *
 * @return array
 *   Filtered menu item labels keyed by menu item ID.
 */
function menu_admin_per_menu_filter_parent_options(AccountInterface $account, array $options) {
  /** @var \Drupal\menu_admin_per_menu\MenuAdminPerMenuAccessInterface $allowedMenusService */
  $allowedMenusService = \Drupal::service('menu_admin_per_menu.allowed_menus');
  $allowed_menus = $allowedMenusService->getPerMenuPermissions($account);

  foreach ($options as $key => $option) {
    list($menu, ) = explode(':', $key, 2);
    if (!in_array($menu, $allowed_menus)) {
      unset($options[$key]);
    }
  }

  return $options;
}
